services:
  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: '${MERCURE_JWT_SECRET}'
      MERCURE_SUBSCRIBER_JWT_KEY: '${MERCURE_JWT_SECRET}'
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins *
        anonymous
    ports:
      - "3000:80"
    volumes:
      - mercure_data:/data
      - mercure_config:/config
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider", "http://localhost:80/.well-known/mercure/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mercure_data:
  mercure_config:
