controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login_check:
    path: /api/login
    methods: ['POST']

room_invite:
    path: /room/invite/{id}
    controller: App\Controller\RoomController::invite
    defaults:
        _signed: true